{
 "title": "SPIRE dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "agent", "query": { "query": "spire_agent_started" } },
   {
    "name": "time",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "instance", "label": "server instance", "query": { "query": "spire_server_started" } }
  ]
 },
 "panels": [
  {
   "title": "Agent (General)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Number of agents per trust domain",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (group (spire_agent_started) by (host, trust_domain_id)) by (trust_domain_id)",
       "legendFormat": "{{trust_domain_id}}"
      }
     ]
    },
    {
     "title": "Number of agents per version",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 6, "x": 7, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count (group (spire_agent_started) by (host, version)) by (version)",
       "legendFormat": "{{version}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Agent",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SPIRE Agent: Trust Domain & Version Info",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (version, trust_domain_id) (spire_agent_started{host=~\"$agent\"}) "
      }
     ]
    },
    {
     "title": "SPIRE Agent: API requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum by (host) (round(increase(spire_agent_rpc_workload_api_fetch_jwt_bundles{host=~\"$agent\"}[$time])))",
       "legendFormat": "fetch jwt bundles, host={{host}}"
      },
      {
       "expr": "sum by (host) (round(increase(spire_agent_rpc_workload_api_fetch_x509_bundles{host=~\"$agent\"}[$time]))) ",
       "legendFormat": "fetch x509 bundles, host={{host}}"
      },
      {
       "expr": "sum by (host) (round(increase(spire_agent_rpc_workload_api_fetch_jwtsvid{host=~\"$agent\"}[$time])))",
       "legendFormat": "fetch jwtsvid, host={{host}}"
      }
     ]
    },
    {
     "title": "SPIRE Agent: GET JWT status",
     "type": "piechart",
     "description": "The graph will show the status of request between in the range [toValue-time, toValue]",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (round(increase(spire_agent_rpc_workload_api_fetch_jwtsvid{host=~\"$agent\"}[$time] ) ))"
      }
     ]
    },
    {
     "title": "SPIRE Agent: GET x509 status",
     "type": "piechart",
     "description": "The graph will show the status of request between in the range [toValue-time, toValue]",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (round(increase(spire_agent_rpc_workload_api_fetch_x509svid{host=~\"$agent\"}[$time] ) )) "
      }
     ]
    },
    {
     "title": "SPIRE Agent: Sync SVIDs status",
     "type": "piechart",
     "description": "The graph will show the status of request between in the range [toValue-time, toValue]",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (round(increase(spire_agent_manager_sync_fetch_svids_updates{host=~\"$agent\"}[$time])))"
      }
     ]
    },
    {
     "title": "SPIRE Agent: Sync entries status",
     "type": "piechart",
     "description": "The graph will show the status of request between in the range [toValue-time, toValue]",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (round(increase(spire_agent_manager_sync_fetch_entries_updates{host=~\"$agent\"}[$time])))"
      }
     ]
    },
    {
     "title": "SPIRE Agent: SDS open connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "spire_agent_sds_api_connections{host=~\"$agent\"}"
      }
     ]
    },
    {
     "title": "SPIRE Agent: SDS open connection by time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "round(increase(spire_agent_sds_api_connection{host=~\"$agent\"}[$time]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Agent Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SPIRE Agent: Workload API Attestation Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(spire_agent_workload_api_workload_attestation_elapsed_time_sum{host=~\"$agent\", status=\"OK\"}[2m])/rate(spire_agent_workload_api_workload_attestation_elapsed_time_count{host=~\"$agent\", status=\"OK\"}[2m])"
      }
     ]
    },
    {
     "title": "SPIRE Agent: Workload API JWT-SVID Retrieval Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(spire_agent_rpc_workload_api_fetch_jwtsvid_elapsed_time_sum{host=~\"$agent\", status=\"OK\"}[2m])/rate(spire_agent_rpc_workload_api_fetch_jwtsvid_elapsed_time_count{host=~\"$agent\", status=\"OK\"}[2m])"
      }
     ]
    },
    {
     "title": "SPIRE Agent: Sync entries latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(spire_agent_manager_sync_fetch_entries_updates_elapsed_time_sum{host=~\"$agent\", status=\"OK\"}[2m])/rate(spire_agent_manager_sync_fetch_entries_updates_elapsed_time_count{host=~\"$agent\", status=\"OK\"}[2m])"
      }
     ]
    },
    {
     "title": "SPIRE Agent: Sync SVIDs latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(spire_agent_manager_sync_fetch_svids_updates_elapsed_time_sum{host=~\"$agent\", status=\"OK\"}[2m])/rate(spire_agent_manager_sync_fetch_svids_updates_elapsed_time_count{host=~\"$agent\", status=\"OK\"}[2m])"
      }
     ]
    },
    {
     "title": "SPIRE Agent: Workload API X.509-SVID Retrieval Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(spire_agent_rpc_workload_api_fetch_x509svid_elapsed_time_sum{host=~\"$agent\", status=\"OK\"}[2m]) / rate(spire_agent_rpc_workload_api_fetch_x509svid_elapsed_time_count{host=~\"$agent\", status=\"OK\"}[2m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Agent Runtime info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SPIRE Agent Runtime: Alloc bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spire_agent_runtime_alloc_bytes{host=~\"$agent\"}"
      }
     ]
    },
    {
     "title": "SPIRE Agent Runtime: Heap objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spire_agent_runtime_heap_objects{host=~\"$agent\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server (General)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "SPIRE Server: Trust Domain & Version Info",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by  (host, trust_domain_id, version) (spire_server_started)"
    }
   ]
  },
  {
   "title": "SPIRE Server Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "spire_server_uptime_in_ms{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SPIRE Server: Agent API requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "sum by (instance) (round(increase(spire_server_rpc_agent_v1_agent_attest_agent{instance=~\"$instance\"}[$time])))",
       "legendFormat": "attest, instance={{instance}}"
      },
      {
       "expr": "sum by (instance) (round(increase(spire_server_rpc_agent_v1_agent_renew_agent{instance=~\"$instance\"}[$time])))",
       "legendFormat": "renew, instance={{instance}}"
      }
     ]
    },
    {
     "title": "SPIRE Server: Entry API requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "sum by (instance) (round(increase(spire_server_rpc_entry_v1_entry_batch_create_entry{instance=~\"$instance\"}[$time]))) ",
       "legendFormat": "create, instance={{instance}}"
      },
      {
       "expr": "sum by (instance) (round(increase(spire_server_rpc_entry_v1_entry_batch_delete_entry{instance=~\"$instance\"}[$time])))  ",
       "legendFormat": "delete, instance={{instance}}"
      },
      {
       "expr": "sum by (instance) (round(increase(spire_server_rpc_entry_v1_entry_get_authorized_entries{instance=~\"$instance\"}[$time])))  ",
       "legendFormat": "get, instance={{instance}}"
      },
      {
       "expr": "sum by (instance) (round(increase(spire_server_rpc_entry_v1_entry_list_entries{instance=~\"$instance\"}[$time])))  ",
       "legendFormat": "list, instance={{instance}}"
      }
     ]
    },
    {
     "title": "SPIRE Server: Bundle API requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by (instance) (round(increase(spire_server_rpc_bundle_v1_bundle_get_bundle{instance=~\"$instance\"}[$time]))) ",
       "legendFormat": "get, instance={{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SPIRE Server: Synchronization Latency (Entry Retrieval)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "(rate(spire_server_rpc_entry_v1_entry_get_authorized_entries_elapsed_time_sum{instance=~\"$instance\"}[2m])) / (rate(spire_server_rpc_entry_v1_entry_get_authorized_entries_elapsed_time_count{instance=~\"$instance\"}[2m]))"
      }
     ]
    },
    {
     "title": "SPIRE Server: JWT-SVID Signing Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(spire_server_rpc_svid_v1_svid_new_jwtsvid_elapsed_time_sum{instance=~\"$instance\"}[2m]) / rate(spire_server_rpc_svid_v1_svid_new_jwtsvid_elapsed_time_count{instance=~\"$instance\"}[2m])"
      }
     ]
    },
    {
     "title": "SPIRE Server: X.509-SVID Signing Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(spire_server_rpc_svid_v1_svid_batch_new_x509svid_elapsed_time_sum{instance=~\"$instance\"}[2m]) / rate(spire_server_rpc_svid_v1_svid_batch_new_x509svid_elapsed_time_count{instance=~\"$instance\"}[2m])"
      }
     ]
    },
    {
     "title": "SPIRE Server: Entry Cache Reload Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(spire_server_entry_cache_reload_elapsed_time_sum{instance=~\"$instance\"}[2m])/rate(spire_server_entry_cache_reload_elapsed_time_count{instance=~\"$instance\"}[2m])"
      }
     ]
    },
    {
     "title": "SPIRE Server: Datastore Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(spire_server_datastore_registration_entry_list_elapsed_time_sum{instance=~\"$instance\"}[2m])/rate(spire_server_datastore_registration_entry_list_elapsed_time_count{instance=~\"$instance\"}[2m])"
      }
     ]
    },
    {
     "title": "SPIRE Server: Bundle Retrieval Latency",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "rate(spire_server_rpc_bundle_v1_bundle_get_bundle_elapsed_time_sum{instance=~\"$instance\"}[2m])/rate(spire_server_rpc_bundle_v1_bundle_get_bundle_elapsed_time_count{instance=~\"$instance\"}[2m])"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Runtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "SPIRE Server Runtime: Alloc bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spire_server_runtime_alloc_bytes{instance=~\"$instance\"}"
      }
     ]
    },
    {
     "title": "SPIRE Server Runtime: Heap objects",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "spire_server_runtime_heap_objects{instance=~\"$instance\"}"
      }
     ]
    }
   ]
  }
 ]
}